GET http://localhost:5181/games

###
GET http://localhost:5181/games/1

###
POST http://localhost:5181/games
Content-Type: application/json

{
    "Name": "FIFA 23",
    "GenreId": 5,
    "Price": 69.99,
    "ReleaseDate": "2022-09-27"
}

###
PUT http://localhost:5181/games/1
Content-Type: application/json

{
    "Name": "Call of Duty",
    "GenreId": 1,
    "Price": 49.99,
    "ReleaseDate": "2013-07-15"
}

###
DELETE http://localhost:5181/games/3


